version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://denifer:admin123@mongodb-demo.p1jch.mongodb.net/?retryWrites=true&w=majority&appName=mongodb-demo
      - JWT_SECRET=
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    depends_on:
      - client

  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
